# Generated by Django 4.2.11 on 2024-03-31 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_technologies_user_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название вакансии')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='дата начала диапазона возраста участников')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='дата конец диапазона возраста участников')),
                ('skills', models.ManyToManyField(blank=True, to='users.skill', verbose_name='Технологии')),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.specialization', verbose_name='специализация')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='описание команды')),
                ('name', models.CharField(max_length=255, verbose_name='название команды')),
                ('avatar', models.ImageField(blank=True, upload_to='teams_avatars', verbose_name='аватарка')),
                ('count_of_members', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxLengthValidator(5)], verbose_name='количество участников')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='страна')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='город')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='участники')),
                ('vacancies', models.ManyToManyField(to='teams.vacancy', verbose_name='вакансии')),
            ],
        ),
    ]
