# Generated by Django 4.2.11 on 2024-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_online",
            field=models.BooleanField(default=True, verbose_name="оффлайн или онлайн"),
        ),
        migrations.AddField(
            model_name="event",
            name="limitation",
            field=models.CharField(
                choices=[
                    ("Everyone", "everyone"),
                    ("School", "school"),
                    ("Student", "student"),
                    ("Professional", "professional"),
                ],
                default="everyone",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(default="", max_length=512),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
