# Generated by Django 5.0.3 on 2024-03-31 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='technologies',
            new_name='skills',
        ),
    ]
